pipeline {
    agent {
        kubernetes {
            label 'ansible-agent'
            defaultContainer 'ansible'
            containerTemplate {
                name 'ansible'
                image 'artamonovdima/application_agent:4.0'
                ttyEnabled true
                command 'cat'
            }
            serviceAccount 'jenkins-service-account'
            namespace 'jenkins'
        }
    }

    stages {
        stage('Clone Repositories') {
            steps {
                dir('config') {
                    git branch: 'DI-34-Develop', credentialsId: 'ssh_privatekey_github', url: 'git@github.com:iviul/Config.git'
                    sh 'ls -la'
                    sh 'pwd'
                }
                dir('ansible') {
                    git branch: 'main', url: 'https://github.com/qjsoq/Ansible-repo.git'
                    sh 'ls -la'
                    sh 'pwd'
                }
                dir('ansible') {
                    sh 'cp "../config/config-kuber.json" .'
                }
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh '''
                    ansible-playbook "/home/jenkins/agent/workspace/${JOB_NAME}/ansible/app_deploy.yml" -e "env=production"
                '''
            }
        }
    }
}
