controller:
  image: 
    registry: "docker.io"
    repository: "artamonovdima/jenkins-custom"
    tag: "3.0"
    pullPolicy: "IfNotPresent"
  installPlugins: false
  JCasC:
    enabled: true

    configScripts:
      custom-casc.yaml: |
        jenkins:
          systemMessage: "Jenkins configured automatically by JCasC\n\n"
          securityRealm:
            local:
              users:
                - id: "admin"
                  password: "adminich7788"

        credentials:
          system:
            domainCredentials:
              - credentials:
                  - basicSSHUserPrivateKey:
                      scope: GLOBAL
                      id: "ssh_privatekey_github"
                      username: "git"
                      description: "SSH key for GitHub access"
                      privateKeySource:
                        directEntry:
                          privateKey: ${JENKINS_GITHUB_SSH_PRIVATE_KEY}

        jobs:
          - script: >
              pipelineJob('Main Pipeline Job') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/qjsoq/Jenkins-Automation.git')
                        }
                        branches('*/main')
                      }
                    }
                    scriptPath('jenkins/application/Jenkinsfile')
                  }
                }
              }
          - script: >
              pipelineJob('Infrastructure Pipeline Job') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/qjsoq/Jenkins-Automation.git')
                        }
                        branches('*/main')
                      }
                    }
                    scriptPath('jenkins/infra/Jenkinsfile')
                  }
                }
              }
              
        security:
          gitHostKeyVerificationConfiguration:
            sshHostKeyVerificationStrategy: "acceptFirstConnectionStrategy"
  sidecars:
    configAutoReload:
      enabled: true

  serviceAccount:
    create: true
rbac:
  create: true